#' Deal Cards to UNO Players
#'
#' Randomly shuffles a UNO deck and distributes 7 cards to each player.
#' Cards are dealt in 7 sequential rounds, one card at a time to each player,
#' maintaining fairness in order. After dealing, the function also initializes the
#' discard pile by placing one card from the remaining deck face-up.
#'
#' This function is commonly used as the first step in setting up a game using
#' \code{\link{setup_game}} or \code{\link{play_game}}.
#'
#' @param deck A tibble representing a full UNO deck as generated by
#'   \code{\link{create_uno_deck}}. Must contain 108 UNO cards with columns:
#'   \code{color}, \code{value}, and \code{type}.
#'
#' @param n_players An integer indicating the number of players in the game.
#'   The default is 4, which reflects the standard size for quick simulations. \cr
#'   This version supports any number of players (≥2) based on deck size. \cr
#'   \strong{Note:} Future versions of this package aim to support larger player
#'   counts with built-in validation and dynamic rule adaptation.
#'
#' @details
#' - The cards are dealt using a nested loop: one card per player per round, repeated 7 times. \cr
#' - Each player's hand is stored in a named list (e.g., \code{Player_1}, \code{Player_2}, etc.). \cr
#' - One card is moved from the remaining deck to serve as the opening discard card. \cr
#'
#' The result can be passed directly to downstream functions like
#' \code{\link{play_turns_loop}} to simulate gameplay.
#'
#' @return
#' A named list with the following components:
#' \itemize{
#'   \item \strong{hands} – A named list of tibbles, each containing 7 cards dealt to a player. Names follow the format \code{"Player_1"}, \code{"Player_2"}, etc.
#'   \item \strong{deck} – A tibble representing the remaining draw pile after all hands and the discard card have been removed.
#'   \item \strong{discard} – A one-row tibble containing the top card placed on the discard pile at the start of the game.
#' }
#'
#' @examples
#' # Generate a new UNO deck
#' deck <- create_uno_deck()
#'
#' # Deal cards to 4 players
#' deal <- deal_hands(deck, 4)
#'
#' # View player 1's hand
#' deal$hands$Player_1
#'
#' # View top of discard pile
#' deal$discard
#'
#' # Check hand sizes (should all be 7)
#' sapply(deal$hands, nrow)
#'
#' # Examine remaining deck structure
#' str(deal$deck)
#'
#' @export
deal_hands <- function(deck, n_players = 4) {
  # Deck Shuffling
  deck <- deck[sample(nrow(deck)), ]

  #   Intialize individual hands of players
  hands <- vector("list", n_players)
  for (i in 1:n_players) {
    hands[[i]] <- deck[0, ]
  }
  names(hands) <- paste0("Player_", 1:n_players)

  #Distribute cards per rounds
  for (round in 1:7) {
    for (i in 1:n_players) {
      hands[[i]] <- rbind(hands[[i]], deck[1, ])
      deck <- deck[-1, ]
    }
  }

  # Remainig cards
  discard <- deck[1, , drop = FALSE]

  #Revome 1st card after show
  deck <- deck[-1, ]

  return(list(
    hands = hands,
    deck = deck,
    discard = discard
  ))
}
