# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_card_values <- function(values) {
    .Call('_uno_score_card_values', PACKAGE = 'uno', values)
}

